# Generated by Django 5.0 on 2023-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceno', models.ImageField(upload_to='')),
                ('servicename', models.CharField(max_length=64)),
                ('servicerate', models.ImageField(upload_to='')),
            ],
        ),
    ]
