# Generated by Django 5.0 on 2023-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicerate',
            field=models.FloatField(),
        ),
    ]
